### PR TITLE
Add heftymouse's DiscordHub link

### PR DESCRIPTION
**Pull request by itsWindows11**

### CODE REVIEW

**Comment by heftymouse** [comment]
I'd rather not have mine there since that site is cursed
In fact we were considering removing it entirely for all mods

**Comment by cleverActon0126** [comment]
Is there any alternatives sites like that that is available? I was thinking of dsc.bio but that isn't the best tbh.

**Comment by itsWindows11** [comment]
> Is there any alternatives sites like that that is available? I was thinking of dsc.bio but that isn't the best tbh.

Hmm not really, there's discord.id but that requires you to find the user's ID and look it up.

**Comment by Erisa** [comment]
The one I had in mind most recently was https://discordlookup.com/user/228574821590499329

**Comment by itsWindows11** [comment]
Also I think that's out of scope for this PR?

**Comment by Erisa** [comment]
Absolutely, it's a discussion we will have ourselves, thanks

**Comment by Erisa** [comment]
Closing since hefty doesn't want theirs on the site

**Comment by itsWindows11** [comment]
Hmm okay

**Pull request closed without merging**
