### PR TITLE
Made most wiki images take up the entire article's available width.

### PR DESCRIPTION
**Pull request by itsWindows11**
In most articles we add images in plain HTML syntax just to specify width. In VuePress, there wasn't any limited width for article containers. VitePress has a max width of 688px (as of the time of the commit) for article containers. Thus it's unnecessary to limit image width, and may make some images unreadable without zooming on desktops.

### CODE REVIEW

**Comment by sthivaios** [comment]
What if VitePress gets an update in the future that changes that "limit" and then the images look way too big again?

**Also,** what happens to smaller images? Do they just get resized to max?

**Comment by Erisa** [comment]
> What if VitePress gets an update in the future that changes that "limit" and then the images look way too big again?

That would be caught in the review process for a potential update (we pin the version of Vitepress) and can be handled there.

**Comment by sthivaios** [comment]
> > What if VitePress gets an update in the future that changes that "limit" and then the images look way too big again?
> 
> That would be caught in the review process for a potential update (we pin the version of Vitepress) and can be handled there.

I meant that it would be a hassle to change them back to HTML if that happened. In that case we could also just not update VitePress of course but tbh it is unlikely that they will update it anyway ig.

**Review by Erisa — APPROVED** [review]
Thanks, the images seem fine

**Pull request merged**
