### PR TITLE
Added Jim into Moderators 

### PR DESCRIPTION
**Pull request by cleverActon0126**

### CODE REVIEW

**Comment by cleverActon0126** [comment]
I don't know why but it also included the last PR I already created (:waitwhat:) *anyways*

**Review by Erisa — APPROVED** [review]

**Comment by cleverActon0126** [comment]
I don't have Jim's profile so I didn't link anything

**Comment by Erisa** [comment]
It's fine for now. Last I check Jim didn't have a profile on that site so there's no point linking anything. That can be sorted later if a page is found, the important thing for now is to get it qdded. Which this PR does.

**Comment by cleverActon0126** [comment]
True.

**Pull request merged**
