### PR TITLE
Remove Common Misconceptions article

### PR DESCRIPTION
**Pull request by heftymouse**
The tone and style of the article is not befitting of a wiki and consists of many half-truths or falsehoods and redundant information.

### CODE REVIEW

**Comment by Erisa** [comment]
Please can you elaborate? I approved this article when it was first approved and did not find that anything was outright incorrect at the time.

The "tone and style" doesn't really matter since all wiki pages are intentionally community created and we shouldn't be policing them too heavily.

**Comment by heftymouse** [comment]
The RAM utilization section combines some truths with anecdotal evidence - it argues that high memory usage is due to file caching, but the 'high memory usage' that the vast majority of users take note of consists only of what is actively in use by programs. (I've elaborated on Discord a bit)

The bloatware section is fine, no problems there in my eyes.

The forced updates section is fine in terms of content but feels a bit out of place, as if it's for people who haven't used a modern version of Windows but still want to criticize it, which in my opinion isn't really a group worth addressing. Same goes for the updates requiring a restart section, although it has the added issue of saying WU 'mostly contains kernel updates', Windows is a less monolithic system like Linux and using kernel as an umbrella term for all system updates is inaccurate.

The advertisements section is just a defense of ads in Windows - whatever the motive, form or monetary cost, all the examples listed are ads.

The feedback hub section is great, no problems there either.

As for tone and style, in this particular case I believe that it's worth policing.

**Review by torchgm — CHANGES_REQUESTED** [review]
Blindly removing this section seems wholly-unnecessary to me - the whole point of it was to be able to direct users in its direction citing different sections as applicable to minimise the spread of misinformation. If there's anything inherently incorrect in the provided information then updating it to be accurate would be much more useful.

With the advertising, not everything is listed is by definition an advertisement. There is a legal difference between advertisement and promotion in most parts of the world, something that most overlook. Besides that, it is a defence, yes. That's the point. A common misconception is that Windows advertises _more_ than other companies ergo making it inherently bad or worse than the competition. This isn't the case and instead is more-or-less on-par with said competition in terms of their internal promotion and external advertising. I do however agree this explanation could be made clearer in summarising this section.

As for tone, this article is inherently designed to be more casual - it's a substitute for a 30-minute-long conversation on bloatware of memory utilisation etc., not a guide. "Policing" writing style when the content is clear is an unnecessary overreach. As long as everything is spelt and formatted correctly then the specifics of how it's written shouldn't matter. This is a community wiki, not a corporate-run FAQ.

If you take issue with this article then I'd strongly recommend you make changes to it rather than attempt to get rid of it. Keep in mind its purpose - it serves to help explain certain topics to users that often get brought up in "haha windows sux" conversations without being overbearing in technical detail. From my perspective this article is in pretty good shape and outside of a slightly better summary for the advertising section and whatever additional fact-checking is required for the memory utilisation section, no major changes are necessary.

**Comment by heftymouse** [comment]
Understandable, I'll do that instead

**Pull request closed without merging**
