### PR TITLE
Started apply form

### PR DESCRIPTION
**Pull request by Danielx64**
Please note that for now it a WIP, so that I can use the site preview feature for testing (and seeing how things look)

### CODE REVIEW

**Comment by Danielx64** [comment]
I don't know whats going on but when I add the javascript to the new page, the page doesn't get created. Am I doing anything wrong?

**Comment by sylveon** [comment]
The free version of netlify forms is a bit inappropriate because it is limited to 100 submissions per month. Our mod applications can blow past that limit and to get more it's 99$ per month.

As for your issue, don't use JQuery. It's 2020.
image

**Comment by Danielx64** [comment]
> 
> 
> The free version of netlify forms is a bit inappropriate because it is limited to 100 submissions per month. Our mod applications can blow past that limit and to get more it's 99$ per month.
> 
> As for your issue, don't use JQuery. It's 2020.
> image

Thank you for the head up, do you know any other options that are out there? I can see why Microsoft Forms was used, just looking at having everything all intergrated together with links etc.

**Comment by sylveon** [comment]
A netlify function calling a discord webhook

**Comment by Jasius** [comment]
There's no plans to migrate mod form due to reasons that @sylveon mentioned and in general MS forms is a lot more appropriate way to handle this.

**Pull request closed without merging**
